-- MySQL Workbench Synchronization
-- Generated: 2017-07-08 01:49
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Сирожа и Маха

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `mydb`.`Car` 
CHANGE COLUMN `model` `model` VARCHAR(45) NULL DEFAULT NULL COMMENT '' ;

CREATE TABLE IF NOT EXISTS `mydb`.`Part` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `code` VARCHAR(45) NOT NULL COMMENT '',
  `group` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `status` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Car_model` VARCHAR(45) NOT NULL COMMENT '',
  UNIQUE INDEX `code_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `code_UNIQUE` (`code` ASC)  COMMENT '',
  INDEX `fk_Part_Car_idx` (`Car_model` ASC)  COMMENT '',
  PRIMARY KEY (`code`)  COMMENT '',
  CONSTRAINT `fk_Part_Car`
    FOREIGN KEY (`Car_model`)
    REFERENCES `mydb`.`Car` (`model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

DROP TABLE IF EXISTS `mydb`.`engine` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
